version: '3.7'

services: 

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
    - system-network

  # rocstack:
  #   build: ./rocstack
  #   container_name: rocstack
  #   ports:
  #     - 2001:2001
  #   networks:
  #     - system-network

  imbrad:
    build: ./ImBrad
    container_name: imbrad
    ports:
      - 8081:80
    networks:
      - system-network

networks:
  system-network:
    name: system-network