version: '3.7'

services: 

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/error.log:/etc/nginx/error_log.log
      # - ./nginx/cache/:/etc/nginx/cache
      # - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
    - system-network

networks:
  system-network:
    name: system-network